# mengimpor library yang hendak digunakan
1. import pandas as pd: Ini mengimpor library pandas dan memberikan alias 'pd' sehingga Anda dapat menggunakan 'pd' untuk mengakses fungsi dan objek dari library ini. Pandas digunakan untuk analisis data, terutama dengan menggunakan struktur data seperti DataFrames.

2. import numpy as np: Ini mengimpor library numpy dan memberikan alias 'np'. Numpy adalah library yang digunakan untuk melakukan operasi numerik, terutama dengan menggunakan array dan matriks.

3. import matplotlib.pyplot as plt: Ini mengimpor modul pyplot dari library matplotlib dan memberikan alias 'plt'. Matplotlib digunakan untuk membuat visualisasi data seperti grafik dan plot.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import nltk: Ini mengimpor library NLTK (Natural Language Toolkit) ke dalam program Python Anda. NLTK adalah library yang sering digunakan dalam pemrosesan bahasa alami (NLP) dan menyediakan berbagai alat dan sumber daya untuk analisis teks.

nltk.download("stopwords"): Ini adalah perintah yang digunakan untuk mengunduh sumber daya bahasa dari NLTK. Lebih khusus, perintah ini mengunduh daftar kata-kata stop ("stop words") yang umum digunakan dalam pemrosesan teks. Stop words adalah kata-kata seperti "the," "and," "is," dan sejenisnya yang sering diabaikan dalam analisis teks karena kurangnya informasi penting yang mereka bawa.

In [2]:
data =pd.read_csv("clean_data2.csv")
data.head()

Unnamed: 0                                           komentar     kategori  \
0           0  Katanya orang kaya.. makan saja 1 hari 1jt.. t...  hate speech   
1           1  Malu ga sih open donasi, padahal tongkronganga...  hate speech   
2           2  bapak mana mak? Denise : sabar ya nak mama lag...  hate speech   
3           3  ORANG KAYA KOK NGEMIS wkwk. kalau NANTI GA MAM...  hate speech   
4           4  Percuma anak cuma buat dijadiin konten. Sumpah...  hate speech   

   label                                         clean_text  
0      1  orang kaya makan jt open donasi ngemis online ...  
1      1  malu tidak sih open donasi tongkrongangannya i...  
2      1           mak denise sabar ya nak mama buka lowong  
3      1  orang kaya ngemis wkwk tidak ngurus anak taro ...  
4      1  anak dijadiin konten sumpah calon emak mah eks...

In [3]:
x = data['clean_text']
y = data['label']

In [4]:
x

0       orang kaya makan jt open donasi ngemis online ...
1       malu tidak sih open donasi tongkrongangannya i...
2                mak denise sabar ya nak mama buka lowong
3       orang kaya ngemis wkwk tidak ngurus anak taro ...
4       anak dijadiin konten sumpah calon emak mah eks...
                              ...                        
4911    salut banting tulang hidup keluarga duduk bang...
4912    laki laki beneran juang anak istri bahagia ist...
4913    bangga suami istri profesi kau juara sehat goj...
4914                 kerja halal nafkah keluarga semangat
4915    gojek mayoritas pegangguran tidak kerja putus ...
Name: clean_text, Length: 4916, dtype: object

In [5]:
y

0       1
1       1
2       1
3       1
4       1
       ..
4911    0
4912    0
4913    0
4914    0
4915    0
Name: label, Length: 4916, dtype: int64

import pickle: Ini mengimpor library pickle, yang digunakan untuk serialisasi dan deserialisasi objek Python, memungkinkan Anda untuk menyimpan dan mengambil kembali objek-objek tersebut dari file.

from sklearn.feature_extraction.text import TfidfVectorizer: Ini mengimpor modul TfidfVectorizer dari library scikit-learn (sklearn). TfidfVectorizer digunakan untuk mengubah teks menjadi vektor TF-IDF, yang digunakan dalam pemrosesan teks dan analisis teks.

vec_TF_IDF = TfidfVectorizer(ngram_range=(1,1)): Anda membuat sebuah objek vec_TF_IDF yang merupakan instance dari TfidfVectorizer. Parameter ngram_range=(1,1) menunjukkan bahwa Anda ingin menggunakan model unigram, yang berarti hanya kata-kata tunggal yang akan dihitung frekuensinya.

vec_TF_IDF.fit(x): Anda menggunakan objek vec_TF_IDF untuk melakukan fitting pada data x. Ini akan menghitung nilai TF-IDF untuk setiap kata dalam data x.

x_tf_idf = vec_TF_IDF.transform(x): Anda menggunakan objek vec_TF_IDF yang telah di-fit untuk mengubah data x menjadi vektor TF-IDF.

pickle.dump(vec_TF_IDF.vocabulary_, open("feature_tf-idf.sav", "wb")): Dalam langkah ini, Anda menggunakan pickle.dump untuk menyimpan kamus kata-kata yang terkait dengan vektor TF-IDF ke dalam file "feature_tf-idf.sav" dalam mode binary write ("wb"). Kamus ini akan berguna saat Anda ingin mengonversi teks baru menjadi vektor TF-IDF dengan kata-kata yang sama yang telah digunakan dalam training.

Dengan kode ini, Anda telah menyimpan model TF-IDF dan kamus kata-kata yang sesuai ke dalam file "feature_tf-idf.sav", yang dapat Anda gunakan untuk transformasi teks baru ke dalam vektor TF-IDF menggunakan kamus yang sama.

In [6]:
# Save Model
import pickle

#TF-IDF
from sklearn.feature_extraction.text import TfidfVectorizer

#Unigram
vec_TF_IDF = TfidfVectorizer(ngram_range=(1,2))
vec_TF_IDF.fit(x)

x_tf_idf =vec_TF_IDF.transform(x)

pickle.dump(vec_TF_IDF.vocabulary_,open("feature_tf-idf.sav", "wb"))

In [7]:
# Menampilkan vocab dari Tif-idf
vec_TF_IDF.vocabulary_

{'orang': 30113,
 'kaya': 18331,
 'makan': 23517,
 'jt': 16858,
 'open': 30065,
 'donasi': 10542,
 'ngemis': 27757,
 'online': 30023,
 'kedok': 18590,
 'yah': 45216,
 'mbak': 24731,
 'orang kaya': 30305,
 'kaya makan': 18411,
 'makan jt': 23559,
 'jt open': 16868,
 'open donasi': 30067,
 'donasi ngemis': 10573,
 'ngemis online': 27780,
 'online kedok': 30031,
 'kedok donasi': 18592,
 'donasi yah': 10588,
 'yah mbak': 45241,
 'malu': 23794,
 'tidak': 40740,
 'sih': 37335,
 'tongkrongangannya': 42269,
 'iphone': 15754,
 'mewah': 25392,
 'maksud': 23707,
 'banding': 3673,
 'denada': 9429,
 'biaya': 5794,
 'obat': 29755,
 'anak': 1400,
 'sakit': 35117,
 'kera': 19151,
 'buka': 7013,
 'atur': 2766,
 'indonesia': 15473,
 'urus': 43678,
 'absah': 70,
 'syarat': 39169,
 'malu tidak': 23871,
 'tidak sih': 41588,
 'sih open': 37477,
 'donasi tongkrongangannya': 10585,
 'tongkrongangannya iphone': 42270,
 'iphone makan': 15757,
 'makan mewah': 23587,
 'mewah tidak': 25403,
 'tidak maksud': 41245,

In [8]:
print(len(vec_TF_IDF.get_feature_names_out()))

45513


In [9]:
print(vec_TF_IDF.get_feature_names_out())

['aad' 'aad terima' 'aaliyah' ... 'zoom' 'zoom gaya' 'zoom untung']


In [10]:
x1 = vec_TF_IDF.transform(x).toarray()
data_tabular_tf_idf =pd.DataFrame(x1,columns=vec_TF_IDF.get_feature_names_out())
data_tabular_tf_idf

aad  aad terima  aaliyah  aaliyah sahabat  aaliyah thoriq  abadi  \
0     0.0         0.0      0.0              0.0             0.0    0.0   
1     0.0         0.0      0.0              0.0             0.0    0.0   
2     0.0         0.0      0.0              0.0             0.0    0.0   
3     0.0         0.0      0.0              0.0             0.0    0.0   
4     0.0         0.0      0.0              0.0             0.0    0.0   
...   ...         ...      ...              ...             ...    ...   
4911  0.0         0.0      0.0              0.0             0.0    0.0   
4912  0.0         0.0      0.0              0.0             0.0    0.0   
4913  0.0         0.0      0.0              0.0             0.0    0.0   
4914  0.0         0.0      0.0              0.0             0.0    0.0   
4915  0.0         0.0      0.0              0.0             0.0    0.0   

      abadi indonesia  abadi lihat  abadi sukses  abah  ...  zolim  zolimi  \
0                 0.0          0.0           0.0   0.0  ...    0.0     0.0   
1                 0.0          0.0           0.0   0.0  ...    0.0     0.0   
2                 0.0          0.0           0.0   0.0  ...    0.0     0.0   
3                 0.0          0.0           0.0   0.0  ...    0.0     0.0   
4                 0.0          0.0           0.0   0.0  ...    0.0     0.0   
...               ...          ...           ...   ...  ...    ...     ...   
4911              0.0          0.0           0.0   0.0  ...    0.0     0.0   
4912              0.0          0.0           0.0   0.0  ...    0.0     0.0   
4913              0.0          0.0           0.0   0.0  ...    0.0     0.0   
4914              0.0          0.0           0.0   0.0  ...    0.0     0.0   
4915              0.0          0.0           0.0   0.0  ...    0.0     0.0   

      zolimi ludah  zone  zone head  zonk  zonk menu  zoom  zoom gaya  \
0              0.0   0.0        0.0   0.0        0.0   0.0        0.0   
1              0.0   0.0        0.0   0.0        0.0   0.0        0.0   
2              0.0   0.0        0.0   0.0        0.0   0.0        0.0   
3              0.0   0.0        0.0   0.0        0.0   0.0        0.0   
4              0.0   0.0        0.0   0.0        0.0   0.0        0.0   
...            ...   ...        ...   ...        ...   ...        ...   
4911           0.0   0.0        0.0   0.0        0.0   0.0        0.0   
4912           0.0   0.0        0.0   0.0        0.0   0.0        0.0   
4913           0.0   0.0        0.0   0.0        0.0   0.0        0.0   
4914           0.0   0.0        0.0   0.0        0.0   0.0        0.0   
4915           0.0   0.0        0.0   0.0        0.0   0.0        0.0   

      zoom untung  
0             0.0  
1             0.0  
2             0.0  
3             0.0  
4             0.0  
...           ...  
4911          0.0  
4912          0.0  
4913          0.0  
4914          0.0  
4915          0.0  

[4916 rows x 45513 columns]

In [11]:
x_train =np.array(data_tabular_tf_idf)
y_train =np.array(y)

Kode yang Anda berikan adalah contoh penggunaan library scikit-learn (sklearn) untuk melakukan seleksi fitur dengan metode chi-squared (chi2). Ini berguna untuk mengurangi jumlah fitur dalam data Anda menjadi fitur-fitur yang paling relevan. Mari saya jelaskan langkah-langkahnya:

from sklearn.feature_selection import SelectKBest: Ini mengimpor kelas SelectKBest dari sklearn. SelectKBest adalah algoritma seleksi fitur yang memungkinkan Anda untuk memilih fitur-fitur terbaik berdasarkan metrik tertentu.

from sklearn.feature_selection import chi2: Ini mengimpor metrik chi-squared (chi2) yang akan digunakan untuk menilai relevansi fitur.

chi2_features = SelectKBest(chi2, k=2000): Anda membuat sebuah objek chi2_features dari kelas SelectKBest dan mengaturnya untuk menggunakan metrik chi-squared (chi2) dengan memilih 2000 fitur terbaik (k=2000). Ini berarti Anda ingin mempertahankan 2000 fitur terbaik berdasarkan perhitungan chi-squared.

x_kbest_features = chi2_features.fit_transform(x_train, y_train): Anda menggunakan objek chi2_features yang telah dibuat untuk melakukan seleksi fitur pada data pelatihan (x_train dan y_train). Hasil dari seleksi ini disimpan dalam variabel x_kbest_features, yang akan berisi data dengan hanya 2000 fitur terbaik yang telah dipilih.

print("Original Feature Number : ", x_train.shape[1]): Ini mencetak jumlah fitur asli dalam data pelatihan sebelum seleksi fitur dilakukan.

print("Reduced Feature Number: ", x_kbest_features.shape[1]): Ini mencetak jumlah fitur setelah seleksi fitur dilakukan, yang dalam hal ini adalah 2000 fitur terbaik yang dipilih oleh metode chi-squared.

Dengan menggunakan SelectKBest dengan metode chi-squared, Anda dapat mengurangi dimensi data Anda dan mempertahankan hanya fitur-fitur yang paling informatif untuk tugas analisis atau pemodelan berikutnya.

In [12]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2

chi2_features =SelectKBest(chi2, k=276)
x_kbest_features =chi2_features.fit_transform(x_train, y_train)

print("Original Feature Number : ", x_train.shape[1])
print("Reduced Feature Number: ",x_kbest_features.shape[1])

Original Feature Number :  45513
Reduced Feature Number:  276


In [13]:
f_score=chi2(x_train,y_train)
f_score

(array([0.31220844, 0.31220844, 0.34110427, ..., 0.66613805, 0.44576457,
        0.25252069]),
 array([0.57632815, 0.57632815, 0.55919251, ..., 0.41440131, 0.50435318,
        0.61530575]))

In [14]:
pvalues=pd.Series(f_score[0],index=vec_TF_IDF.get_feature_names_out())
pvalues.sort_values(ascending=True,inplace=True)
pvalues

orang mulu    7.020367e-09
gugurin       1.042309e-08
kasihan       4.860814e-07
ondel         5.413676e-07
timur         1.020387e-06
                  ...     
cantik        2.027283e+01
lonte         2.070043e+01
malu          2.743055e+01
tolol         2.789557e+01
goblok        3.828957e+01
Length: 45513, dtype: float64

In [15]:
Data = pd.DataFrame(chi2_features.scores_, columns=['Nilai'])
Data

Nilai
0      0.312208
1      0.312208
2      0.341104
3      0.165570
4      0.191995
...         ...
45508  0.443460
45509  0.205409
45510  0.666138
45511  0.445765
45512  0.252521

[45513 rows x 1 columns]

In [16]:
feature =vec_TF_IDF.get_feature_names_out()
feature

Data['Fitur'] = feature
Data.sort_values(by="Nilai", ascending=False)

Nilai       Fitur
13231  3.828957e+01      goblok
42095  2.789557e+01       tolol
23794  2.743055e+01        malu
22738  2.070043e+01       lonte
7513   2.027283e+01      cantik
...             ...         ...
41814  1.020387e-06       timur
30011  5.413676e-07       ondel
18148  4.860814e-07     kasihan
13408  1.042309e-08     gugurin
30381  7.020367e-09  orang mulu

[45513 rows x 2 columns]

In [17]:
mask =chi2_features.get_support()
mask

array([False, False, False, ..., False, False, False])

In [18]:
#Menampilkan fitur yang terpilih berdasarkan mask atau nilai tertinggi yang sudah ditetapkan chi square

new_feature=[]
for bool, f in zip(mask, feature):
    if bool :
        new_feature.append(f)
    selected_feature=new_feature
selected_feature

['agama',
 'akhlak',
 'akun',
 'ala',
 'alay',
 'alhamdulillah',
 'allah',
 'aman',
 'amanda',
 'amit',
 'anak',
 'anak tolol',
 'aneh',
 'anjing',
 'anjir',
 'apa',
 'arawinda',
 'arhan',
 'athena',
 'attitude',
 'ayah',
 'azab',
 'babi',
 'baby',
 'bacot',
 'bad',
 'bad attitude',
 'bagus',
 'bagus banget',
 'bahagia',
 'bajing',
 'banci',
 'bang',
 'banget',
 'bayi',
 'belagu',
 'beli',
 'bh',
 'bibu',
 'bikin malu',
 'binatang',
 'birah',
 'blokir',
 'bobrok',
 'bocah',
 'bodoh',
 'botak',
 'bu',
 'bumil',
 'bunuh',
 'cakep',
 'cantik',
 'cantik banget',
 'caper',
 'celana',
 'cinta',
 'cuih',
 'dajjal',
 'dasar',
 'definisi',
 'den',
 'denise',
 'dih',
 'dil',
 'doa',
 'dok',
 'dokter',
 'dokter richard',
 'donasi',
 'duta',
 'elit',
 'enak banget',
 'fadil',
 'fia',
 'film',
 'fuji',
 'gala',
 'ganteng',
 'ganteng banget',
 'gapunya',
 'garuk',
 'garuk memek',
 'gaul',
 'geli',
 'gila',
 'goblok',
 'goblok nya',
 'hak',
 'hancur',
 'hapus',
 'hati',
 'hebat',
 'hijab',
 'hujan',


In [19]:
#Membuat vocabulary baru berdasarkan fitur yang terseleksi

new_selected_feature = {}

for (k,v) in vec_TF_IDF.vocabulary_.items():
    if k in selected_feature:
        new_selected_feature[k]=v

new_selected_feature

{'kaya': 18331,
 'open': 30065,
 'donasi': 10542,
 'ngemis': 27757,
 'orang kaya': 30305,
 'open donasi': 30067,
 'malu': 23794,
 'anak': 1400,
 'denise': 9505,
 'sabar': 34955,
 'ya': 44770,
 'mama': 23893,
 'wkwk': 44632,
 'kaya ngemis': 18426,
 'malu lihat': 23839,
 'keluarga': 18757,
 'hati': 14210,
 'bikin malu': 6004,
 'jalan': 16192,
 'bahagia': 3303,
 'bodoh': 6526,
 'sehat': 36066,
 'tolol': 42095,
 'banget': 3752,
 'jijik': 16698,
 'lapor': 21577,
 'akun': 769,
 'baby': 3088,
 'goblok': 13231,
 'sok': 37938,
 'kandung': 17778,
 'ka': 17115,
 'den': 9378,
 'cantik': 7513,
 'cantik banget': 7528,
 'anjing': 2013,
 'miskin': 25680,
 'celana': 7855,
 'memek': 25037,
 'cinta': 8226,
 'birah': 6311,
 'ngewe': 27910,
 'bayi': 4697,
 'sayang': 35718,
 'bagus': 3231,
 'belagu': 5008,
 'jijik lihat': 16710,
 'tidak malu': 41248,
 'bh': 5607,
 'minimal': 25578,
 'beli': 5057,
 'gapunya': 12645,
 'kak': 17328,
 'kampung': 17690,
 'suka': 38616,
 'aneh': 1863,
 'tau malu': 39928,
 'otak':

In [20]:
len(new_selected_feature)

276

In [21]:
pickle.dump(new_selected_feature,open("new_selected_feature_tf-idf.sav", "wb"))

In [22]:
x_kbest_features

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [23]:
#menampilkan fitur-fitur yang sudah diseleksi

data_selected_feature =pd.DataFrame(x_kbest_features, columns=selected_feature)
data_selected_feature

agama  akhlak  akun  ala  alay  alhamdulillah  allah  aman  amanda  \
0       0.0     0.0   0.0  0.0   0.0            0.0    0.0   0.0     0.0   
1       0.0     0.0   0.0  0.0   0.0            0.0    0.0   0.0     0.0   
2       0.0     0.0   0.0  0.0   0.0            0.0    0.0   0.0     0.0   
3       0.0     0.0   0.0  0.0   0.0            0.0    0.0   0.0     0.0   
4       0.0     0.0   0.0  0.0   0.0            0.0    0.0   0.0     0.0   
...     ...     ...   ...  ...   ...            ...    ...   ...     ...   
4911    0.0     0.0   0.0  0.0   0.0            0.0    0.0   0.0     0.0   
4912    0.0     0.0   0.0  0.0   0.0            0.0    0.0   0.0     0.0   
4913    0.0     0.0   0.0  0.0   0.0            0.0    0.0   0.0     0.0   
4914    0.0     0.0   0.0  0.0   0.0            0.0    0.0   0.0     0.0   
4915    0.0     0.0   0.0  0.0   0.0            0.0    0.0   0.0     0.0   

      amit  ...  urat  urat malu  uti  victim      wkwk  wow        ya  \
0      0.0  ...   0.0        0.0  0.0     0.0  0.000000  0.0  0.000000   
1      0.0  ...   0.0        0.0  0.0     0.0  0.000000  0.0  0.000000   
2      0.0  ...   0.0        0.0  0.0     0.0  0.000000  0.0  0.102553   
3      0.0  ...   0.0        0.0  0.0     0.0  0.228091  0.0  0.000000   
4      0.0  ...   0.0        0.0  0.0     0.0  0.000000  0.0  0.000000   
...    ...  ...   ...        ...  ...     ...       ...  ...       ...   
4911   0.0  ...   0.0        0.0  0.0     0.0  0.000000  0.0  0.000000   
4912   0.0  ...   0.0        0.0  0.0     0.0  0.000000  0.0  0.000000   
4913   0.0  ...   0.0        0.0  0.0     0.0  0.000000  0.0  0.000000   
4914   0.0  ...   0.0        0.0  0.0     0.0  0.000000  0.0  0.000000   
4915   0.0  ...   0.0        0.0  0.0     0.0  0.000000  0.0  0.000000   

      ya allah  ya kak  yaa  
0          0.0     0.0  0.0  
1          0.0     0.0  0.0  
2          0.0     0.0  0.0  
3          0.0     0.0  0.0  
4          0.0     0.0  0.0  
...        ...     ...  ...  
4911       0.0     0.0  0.0  
4912       0.0     0.0  0.0  
4913       0.0     0.0  0.0  
4914       0.0     0.0  0.0  
4915       0.0     0.0  0.0  

[4916 rows x 276 columns]

In [24]:
#data_selected_feature.to_csv("hasilchi2.csv")

In [25]:
selected_x = x_kbest_features
selected_x

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [26]:

import random
from sklearn.model_selection import train_test_split



inisiasi model random forest

In [27]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()

membagi data train, dan data test

In [28]:

x =selected_x
y =data.label

x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=0)

In [29]:
print("Banyaknya x_train : ", len(x_train))
print("Banyaknya x_test : ", len(x_test))
print("Banyaknya y_train : ", len(y_train))
print("Banyaknya y_test : ", len(y_test))

Banyaknya x_train :  3932
Banyaknya x_test :  984
Banyaknya y_train :  3932
Banyaknya y_test :  984


inisiasi model random forest

In [30]:
text_algorithm =RandomForestClassifier()

melatih model random forest

In [31]:
model =text_algorithm.fit(x_train, y_train)

test model

In [32]:
#Masukan library yang dibutuhkan

from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

predicted =model.predict(x_test)

CM =confusion_matrix(y_test, predicted)
print(confusion_matrix(y_test,predicted))
print(classification_report(y_test, predicted))
print(accuracy_score(y_test, predicted))

[[433 102]
 [ 75 374]]
              precision    recall  f1-score   support

           0       0.85      0.81      0.83       535
           1       0.79      0.83      0.81       449

    accuracy                           0.82       984
   macro avg       0.82      0.82      0.82       984
weighted avg       0.82      0.82      0.82       984

0.8201219512195121


In [33]:
# Menyimpan model
pickle.dump(model,open("model_fraud_chi2.sav", "wb"))

In [36]:
data_input =("mungkin dia pake kerudung buat nutupin ketombe sama kutu dikepalanya")
#data_input =text_preprocessing_process(data_input)

#laod
tfidf =TfidfVectorizer

loaded_vec =TfidfVectorizer(decode_error="replace", vocabulary=set(pickle.load(open("new_selected_feature_tf-idf_chi2.sav", "rb"))))

hasil =model.predict(loaded_vec.fit_transform([data_input]))

if(hasil==0):
    s ="Komentar tidak terindikasi Hate Speech"

elif(hasil==1):
    s ="Komentar terindikasi Hate Speech"
else:
    s ="inputan salah"

print("Hasil Prediksi : \n", s)

ValueError: X has 2000 features, but RandomForestClassifier is expecting 276 features as input.

In [ ]:
from sklearn.ensemble import RandomForestClassifier
# Number of trees in random forest
n_estimators = [int(x) for x in np.linspace(start = 10, stop = 500, num = 10)]
# Number of features to consider at every split
max_features = ['auto', 'sqrt', 'log2']
# Maximum number of levels in tree
max_depth = [2,4]
# Minimum number of samples required to split a node
min_samples_split = [2, 5]
# Minimum number of samples required at each leaf node
min_samples_leaf = [1, 2]
# Method of selecting samples for training each tree
bootstrap = [True, False]

# Create the param grid
param_grid = {'n_estimators': n_estimators,
             'max_features': ['sqrt', 'log2'], 
             'max_depth': [2, 4, 8], 
             'min_samples_split': [2, 4], 
             'min_samples_leaf': [1, 2], 
             'bootstrap': [True, False],
              'random_state': [0]
             }
print(param_grid)

rf_Model = RandomForestClassifier(random_state=0)

from sklearn.model_selection import GridSearchCV
rf_Grid = GridSearchCV(estimator = rf_Model, param_grid = param_grid, cv = 3, verbose=2, n_jobs=4)
rf_Grid.fit(x_train, y_train)
rf_Grid.best_params_

{'n_estimators': [10, 64, 118, 173, 227, 282, 336, 391, 445, 500], 'max_features': ['sqrt', 'log2'], 'max_depth': [2, 4, 8], 'min_samples_split': [2, 4], 'min_samples_leaf': [1, 2], 'bootstrap': [True, False], 'random_state': [0]}
Fitting 3 folds for each of 480 candidates, totalling 1440 fits


{'bootstrap': True,
 'max_depth': 8,
 'max_features': 'log2',
 'min_samples_leaf': 1,
 'min_samples_split': 4,
 'n_estimators': 118,
 'random_state': 0}

In [ ]:
# Modelling using best parameter

model2 = RandomForestClassifier(n_estimators=118, bootstrap = True, 
                             criterion= 'entropy',max_features = 'log2', min_samples_split = 4, 
                              min_samples_leaf = 1, random_state=0)

# fit the model to the training set
model2.fit(x_train, y_train)

# Predict on the test set results
y_pred2 = model.predict(x_test)

# Check accuracy score 
from sklearn.metrics import accuracy_score
print('Model accuracy score with decision-trees : {0:0.4f}'. format(accuracy_score(y_test, predicted)))

# Modelling using best parameter

model2 = RandomForestClassifier(n_estimators=118, bootstrap = True, 
                              max_depth = 8, 
                             max_features = 'log2', min_samples_split = 4, 
                              min_samples_leaf = 1, random_state=0)

# fit the model to the training set
model2.fit(x_train, y_train)

# Predict on the test set results
y_pred2 = model2.predict(x_test)

# Check accuracy score 
from sklearn.metrics import accuracy_score
print('Model accuracy score with decision-trees : {0:0.4f}'. format(accuracy_score(y_test, predicted)))

y_pred2_proba= model2.predict_proba(x_test)
y_pred2_proba

###CLASSIFICATION REPORT, CONFUSION MATRIX, AND ACCURACY SCORE ###
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(confusion_matrix(y_test,y_pred2))
print(classification_report(y_test,y_pred2))
print(accuracy_score(y_test, y_pred2))

Model accuracy score with decision-trees : 0.8201
Model accuracy score with decision-trees : 0.8201
[[523  12]
 [254 195]]
              precision    recall  f1-score   support

           0       0.67      0.98      0.80       535
           1       0.94      0.43      0.59       449

    accuracy                           0.73       984
   macro avg       0.81      0.71      0.70       984
weighted avg       0.80      0.73      0.70       984

0.7296747967479674
